# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.1.0
minecraft_version_range=[26.1.0,)

# https://neoforged.net/
neoforge_version=26.1.0.19-beta
neoforge_version_range=[26.1.0.19-beta,)

# Mod Properties
mod_id=witherturnsskeletons
mod_version=1.5.1+26.1
mod_name=WitherTurnsSkeletons
mod_group_id=de.dafuqs
mod_license=MIT
mod_authors=DaFuqs
mod_description=Skeletons that are affected by the Wither effect turn into Wither Skeletons
issue_tracker_url=https://github.com/DaFuqs/WitherTurnsSkeletons/issues
display_url=https://github.com/DaFuqs/WitherTurnsSkeletons